Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "private_network", type: "dhcp"
	config.vm.provision :shell, path: "config-machine.sh", privileged: true
	config.vm.network "forwarded_port", guest: 7474, host: 17474, auto_correct: true
	config.vm.synced_folder "../api", "/srv/api/"
	config.vm.synced_folder "../front-end", "/srv/front-end/"
end